//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TennisScoreCalculationUI.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TennisScoreCalculationUI.Languages.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game ID:.
        /// </summary>
        public static string GameId_ {
            get {
                return ResourceManager.GetString("GameId_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Game ID.
        /// </summary>
        public static string LoadGameId {
            get {
                return ResourceManager.GetString("LoadGameId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referee Panel.
        /// </summary>
        public static string RefereePanel {
            get {
                return ResourceManager.GetString("RefereePanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score Screen.
        /// </summary>
        public static string ScoreScreen {
            get {
                return ResourceManager.GetString("ScoreScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set 1.
        /// </summary>
        public static string Set1 {
            get {
                return ResourceManager.GetString("Set1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set 2.
        /// </summary>
        public static string Set2 {
            get {
                return ResourceManager.GetString("Set2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set 3.
        /// </summary>
        public static string Set3 {
            get {
                return ResourceManager.GetString("Set3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start New Game.
        /// </summary>
        public static string StartNewGame {
            get {
                return ResourceManager.GetString("StartNewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winner in Match: .
        /// </summary>
        public static string Winner {
            get {
                return ResourceManager.GetString("Winner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point for Player A.
        /// </summary>
        public static string WonPointPlayerA {
            get {
                return ResourceManager.GetString("WonPointPlayerA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point for Player B.
        /// </summary>
        public static string WonPointPlayerB {
            get {
                return ResourceManager.GetString("WonPointPlayerB", resourceCulture);
            }
        }
    }
}
